local lsp = require("colejj.java.lsp")
local runner = require("colejj.java.runner")
local commands = require("colejj.java.commands")

local M = {}

function M.setup()
  vim.api.nvim_create_autocmd("FileType", {
    group = vim.api.nvim_create_augroup("colejj-java-keys", { clear = true }),
    pattern = { "java", "kotlin", "xml", "jproperties" },
    callback = function(event)
      local bufnr = event.buf
      local map = function(lhs, rhs, desc)
        vim.keymap.set("n", lhs, rhs, { buffer = bufnr, silent = true, desc = desc })
      end

      map("<leader>jo", lsp.organize_imports, "Imports ordnen")
      map("<leader>jf", function()
        require("conform").format({ lsp_fallback = true, async = false, timeout_ms = 5000 })
      end, "Format (IntelliJ-Profil)")
      map("<leader>ju", lsp.update_project, "Maven neu importieren")
      map("<leader>jh", lsp.health, "JDT.LS Health")
      map("<leader>jW", lsp.reset_workspace, "JDT.LS Workspace reset")
      map("<leader>jn", commands.new_type, "Neuer Typ")
      map("<leader>jI", commands.toggle_impl, "Interface ↔ Impl")
      map("<leader>ji", commands.super_implementation, "Super-Methode")
      map("<leader>jg", function()
        lsp.generate("getters")
      end, "Getter/Setter")
      map("<leader>js", function()
        lsp.generate("tostring")
      end, "toString")
      map("<leader>je", function()
        lsp.generate("equals")
      end, "equals/hashCode")
      map("<leader>jv", function()
        lsp.generate("override")
      end, "Override Methods")
      map("<leader>jB", function()
        commands.check_project(false)
      end, "Build Project")
      map("<leader>jb", function()
        commands.check_project(true)
      end, "Modul + Dependents bauen")
      map("<leader>jS", commands.spring_beans, "Spring Beans / Symbole")

      map("<leader>mr", runner.run_config, "Run-Config (DAP)")
      map("<leader>mR", runner.run_mvn, "Run-Config (mvn exec:java)")
      map("<leader>mk", runner.stop, "Run stoppen")
      map("<leader>me", runner.rerun, "Rerun")
      map("<leader>ma", runner.attach, "Attach :5005")
      map("<leader>mh", runner.hotswap, "HotSwap")
      map("<leader>mu", lsp.update_project, "Maven Reimport")
      map("<leader>mG", function()
        require("colejj.java.classpath").ensure_generated_source_roots()
        vim.notify("Generated-Source-Roots aktualisiert", vim.log.levels.INFO, { title = "colejj.java" })
      end, "Generated Sources in Classpath")
      map("<leader>mK", function()
        require("colejj.java.classpath").ensure_kotlin_output()
        vim.notify("Kotlin-Classpath aktualisiert", vim.log.levels.INFO, { title = "colejj.java" })
      end, "Kotlin-Output in Classpath")
      map("<leader>mc", function()
        require("colejj.java.maven").compile(false)
      end, "Maven compile")
      map("<leader>mi", function()
        require("colejj.java.maven").install(true)
      end, "Maven install -DskipTests")
      map("<leader>mb", function()
        require("colejj.java.maven").rebuild()
      end, "Rebuild Project")
      map("<leader>mt", function()
        require("colejj.java.maven").execute_goal()
      end, "Maven Goal eingeben")
      map("<leader>mT", function()
        require("colejj.java.test").run_module()
      end, "Tests des Moduls")
      map("<leader>md", function()
        require("colejj.java.maven").dependency_tree()
      end, "dependency:tree")
    end,
  })

  vim.keymap.set("n", "<leader>rr", runner.run_config, { desc = "Run-Config starten" })
  vim.keymap.set("n", "<leader>rk", runner.stop, { desc = "Run stoppen" })
  vim.keymap.set("n", "<leader>re", runner.rerun, { desc = "Rerun" })
  vim.keymap.set("n", "<leader>rh", runner.hotswap, { desc = "HotSwap" })
  vim.keymap.set("n", "<leader>da", runner.attach, { desc = "Attach :5005" })
  vim.keymap.set("n", "<leader>dQ", runner.stop, { desc = "Alles stoppen" })
end

return M
